language: julia
os:
    - linux
    - osx
julia:
    - 1.3
    - nightly
matrix:
    allow_failures:
        - julia: nightly
    fast_finish: true
notifications:
    email: false
script: 
    - julia -e 'using Pkg; Pkg.build(; verbose=true)'
    - echo 3 | julia -e 'using Pkg; Pkg.test(coverage=true)'
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage")'
    - julia -e 'using Coverage; Coveralls.submit(process_folder())'
