language: julia

coveralls: true

os:
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

env:
  matrix:
    - PYTHON=python3

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip3 install setuptools wandb

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

notifications:
  email: false
