name = "WeightsAndBiasLogger"
uuid = "71805093-c1fc-4af5-8d0a-8dde53c6ac46"
authors = ["Kai Xu <xukai921110@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.0, 2"
julia = "0.7, 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
