name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.5, 1.1.1, 1.2.0, 1.3.0, 1.4.0, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
